# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Viral Jogani
tagline:          'Designer + Developer'
description:      'ECE major at Rutgers University. Web developer and designer.'
url:              http://virjog.github.io

author:
  name:           'Viral Jogani'
  url:            https://twitter.com/virjog

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/virjog/virjog.github.io
