# Site settings
title: "Viral Jogani"
email: viraljogani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://virjog.github.io" # the base hostname & protocol for your site
twitter_username: virjog
github_username:  virjog

# Build settings
markdown: kramdown
permalink: ":title/"
gems: [jekyll-paginate]

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
